import asyncio

from cac.mcp.instance import mcp
from cac.mcp.server import main  # noqa: F401  -- import triggers world/prime registration


def test_all_domain_tools_are_registered() -> None:
    tools = asyncio.run(mcp.list_tools())
    tool_names = {tool.name for tool in tools}

    assert tool_names == {
        "world_get",
        "world_set",
        "world_set_body",
        "prime_get",
        "prime_applicable_lore",
        "lore_get",
        "lore_list",
        "lore_create",
        "lore_update",
        "lore_delete",
        "lore_set_summary",
        "lore_assign_world",
        "lore_unassign_world",
        "lore_assign_region",
        "lore_unassign_region",
        "lore_enable",
        "lore_disable",
        "region_get",
        "region_list",
        "region_create",
        "region_update",
        "region_delete",
        "region_set_summary",
        "region_set_path",
        "campaign_get",
        "campaign_list",
        "campaign_create",
        "campaign_update",
        "campaign_delete",
        "campaign_open",
        "campaign_pause",
        "campaign_complete",
        "campaign_abandon",
        "campaign_archive",
        "encounter_get",
        "encounter_list",
        "encounter_order",
        "encounter_create",
        "encounter_update",
        "encounter_delete",
        "encounter_review",
        "encounter_open",
        "encounter_record_message",
        "encounter_complete",
        "encounter_abandon",
        "encounter_assign_region",
        "encounter_unassign_region",
        "encounter_assign_dependency",
        "encounter_unassign_dependency",
        "index_status",
        "index_search",
        "docs_list",
        "docs_get",
    }
