import re

SOURCEBOOK_DIR_NAME = ".sourcebook"
LORE_DIR_NAME = "lore"
REGION_DIR_NAME = "region"
CAMPAIGN_DIR_NAME = "campaigns"
ENCOUNTER_DIR_NAME = "encounters"
NAME_PATTERN = re.compile(r"^[A-Za-z0-9_.-]+$")
RESERVED_NAMES = frozenset({".", ".."})
WORLD_FILE_NAME = "world.md"
SCHEMA_VERSION_KEY = "schema_version"
SOURCEBOOK_SCHEMA_VERSION = 1
MCP_CONFIG_FILE_NAME = ".mcp.json"
CLAUDE_SETTINGS_FILE_NAME = ".claude/settings.json"
CODEX_CONFIG_FILE_NAME = ".codex/config.toml"
CLAUDE_SKILLS_DIR_NAME = ".claude/skills"
CODEX_SKILLS_DIR_NAME = ".agents/skills"
SKILL_FILE_NAME = "SKILL.md"
SKILL_NAMES = ("world-manager", "campaign-manager")
MCP_SERVER_NAME = "crypts-and-commits"
CAC_MCP_SCRIPT_NAME = "cac-mcp"
SUMMARY_KEY = "summary"
SUMMARY_MAX_LENGTH = 500
CREATED_BY_KEY = "created_by"
CREATED_ON_KEY = "created_on"
UPDATED_BY_KEY = "updated_by"
UPDATED_ON_KEY = "updated_on"
RESPONSE_BUDGET = 20_000
DOCS_RESPONSE_BUDGET = 40_000
CAMPAIGN_STATUSES = ("draft", "open", "paused", "completed", "abandoned")
DEFAULT_CAMPAIGN_STATUS = "draft"
ENCOUNTER_STATUSES = ("draft", "reviewed", "open", "completed", "abandoned")
DEFAULT_ENCOUNTER_STATUS = "draft"
SEARCH_INDEX_DIR_NAME = ".index"
SEARCH_INDEX_DB_NAME = "sourcebook.db"
SEARCH_INDEX_FTS_TABLE = "sourcebook_fts"
SEARCH_INDEX_OBJECT_TYPE_ENCOUNTER = "encounter"
SEARCH_INDEX_OBJECT_TYPE_WORLD = "world"
SEARCH_INDEX_OBJECT_TYPE_LORE = "lore"
SEARCH_INDEX_OBJECT_TYPE_REGION = "region"
SEARCH_INDEX_OBJECT_TYPES = (
    SEARCH_INDEX_OBJECT_TYPE_ENCOUNTER,
    SEARCH_INDEX_OBJECT_TYPE_WORLD,
    SEARCH_INDEX_OBJECT_TYPE_LORE,
    SEARCH_INDEX_OBJECT_TYPE_REGION,
)
SEARCH_DEFAULT_MAX_RESULTS = 10
SEARCH_DEFAULT_SNIPPET_TOKENS = 20
SEARCH_MIN_SNIPPET_TOKENS = 1
SEARCH_MAX_SNIPPET_TOKENS = 64
SEARCH_INDEX_BUSY_TIMEOUT_MS = 5000
